complexity:
  LongMethod:
    threshold: 120
  LongParameterList:
    constructorThreshold: 42
    functionThreshold: 12
  TooManyFunctions:
    thresholdInClasses: 24
  NestedBlockDepth:
    threshold: 5

naming:
  FunctionNaming:
    ignoreAnnotated: [ "Test", "Composable" ]
  TopLevelPropertyNaming:
    constantPattern: "^[A-Z][A-Z0-9_]*"
  PackageNaming:
    packagePattern: "[a-z0-9_.]*"
  ClassNaming:
    classPattern: "^[A-Z][a-zA-Z0-9]*"

performance:
  SpreadOperator:
    active: false

style:
  NewLineAtEndOfFile:
    active: false
  ReturnCount:
    max: 3
  WildcardImport:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    maxDestructuringEntries: 4